### ISSUE TITLE
underscore folder problem with github pages

### ISSUE THREAD

**Issue by spazola** [nextbigsoundinc/stylemark#65]
The stylemark folder starting with an underscore cause problem with github pages.

Files in that folder aren't loaded when you use github pages for you documentation.

**Comment by stefankunze** [comment]
Simply add a `.nojekyll` file in the styleguide directory. This will solve your issue.

[github blogpost](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/)

**Comment by spazola** [comment]
Fixed with .nojekyll file, thank you !

**Comment by kbradley** [comment]
I had the same issue and tried adding a .nojekyll file both to the root of my Github pages repo and also within the "docs" folder where I output stylemark files for my project. Neither has worked and I get 404s on my github page for all the files in the "_stylemark" directory.

Would it be possible just to rename the directory to "stylemark" without the underscore so that all this isn't necessary to begin with?

(I experimented with manually renaming the directory and references to it which worked but isn't a good long term solution...)

**Comment by kbradley** [comment]
I wrote the above too soon. GIthub finally recognized the file and my Stylemark github page is finally working. This was a big headache to discover the cause and how to fix though so respectfully I'd still like to request the directory be renamed if possible to help others avoid this issue in the future. Thanks.
